apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mdb
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: api
