apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mdb
spec:
  type: LoadBalancer
  loadBalancerIP: 161.97.165.65  # Presuming your environment supports specifying this
  ports:
    - name: http
      protocol: TCP
      port: 8080  # The external service port
      targetPort: 8081  # The pod's port where the service sends traffic
  selector:
    app: api
