apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mdb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080  # Specify only if you need a particular node port, within the allowed range.
  selector:
    app: api
