apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mdb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0    # No pods are unavailable during the update
      maxSurge: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/ivosieme/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "150m"  # Requesting 100 millicores
              memory: "512Mi"
            limits:
              cpu: "320m"
              memory: "1024Mi"
          env:
            - name: APP_ENV
              value: 'prod'
            - name: DB_ACCESS_STRING
              valueFrom:
                secretKeyRef:
                  name: db-access-string
                  key: db-access-string
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-name
                  key: db-name
      imagePullSecrets:
        - name: ghcr-creds
