apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
  namespace: mdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
    namespace: mdb
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
