apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/ivosieme/mdb-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_ACCESS_STRING
              valueFrom:
                secretKeyRef:
                  name: db-access-string
                  key: db-access-string
                  namespace: mdb
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-name
                  key: db-name
                  namespace: mdb
      imagePullSecrets:
        - name: ghcr-creds
