apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: ghcr.io/ivosieme/spring-boot-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_ACCESS_STRING
              valueFrom:
                secretKeyRef:
                  name: db_access_string
                  key: db_access_string
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db_name
                  key: db_name
      imagePullSecrets:
        - name: ghcr-creds
