apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: ghcr.io/ivosieme/spring-boot-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_ACCESS_STRING
              value: $(DB_ACCESS_STRING)
            - name: DB_NAME
              value: $(DB_NAME)
      imagePullSecrets:
        - name: ghcr-creds
