version: '3.5'

networks:
  mdb-network:
    name: mdb-network

services:
  mdb-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    platform: linux/x86_64
    ports:
      - "8081:8081"
    networks:
      - mdb-network
