name: Spring Boot CI

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: Check out the repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_ACCESS_STRING: ${{ secrets.DB_ACCESS_STRING }}
        run: ./mvnw test

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/api:latest

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/${{ github.repository_owner }}/api:latest

      - name: Set up Kubeconfig
        if: github.ref == 'refs/heads/main'
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
        run: |
          echo "$KUBECONFIG_CONTENTS" > ./kubeconfig
          echo "KUBECONFIG_FILE=./kubeconfig" >> $GITHUB_ENV

      - name: Apply Kubernetes Deployment
        if: github.ref == 'refs/heads/main'
        run: kubectl --kubeconfig $KUBECONFIG_FILE apply -f api-deployment.yaml -n mdb || true
        env:
          KUBECONFIG_FILE: ${{ env.KUBECONFIG_FILE }}

      - name: Apply Kubernetes Service
        if: github.ref == 'refs/heads/main'
        run: kubectl --kubeconfig $KUBECONFIG_FILE apply -f api-service-loadbalancer.yaml -n mdb || true
        env:
          KUBECONFIG_FILE: ${{ env.KUBECONFIG_FILE }}

      - name: Apply Kubernetes Horizontal Pod Autoscaler
        if: github.ref == 'refs/heads/main'
        run: kubectl --kubeconfig $KUBECONFIG_FILE apply -f api-hpa.yaml -n mdb || true
        env:
          KUBECONFIG_FILE: ${{ env.KUBECONFIG_FILE }}

      - name: Delete existing service if it exists
        run: kubectl --kubeconfig $KUBECONFIG_FILE delete service api-loadbalancer -n mdb || true

      - name: Expose deployment
        if: github.ref == 'refs/heads/main'
        run: |
          kubectl --kubeconfig $KUBECONFIG_FILE delete service api --namespace=mdb
          kubectl --kubeconfig $KUBECONFIG_FILE expose deployment api --namespace=mdb --type=LoadBalancer --port=8080 --target-port=8081
        env:
          KUBECONFIG_FILE: ./kubeconfig
