name: Spring Boot CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: ./mvnw test

    - name: Build Docker image
      run: docker build . -t spring-boot-app

    - name: Run Docker container
      run: docker run -d --name spring-boot-testing -p 8080:8080 spring-boot-app

    - name: Health check
      run: sleep 30 # Adjust based on your app's startup time
