name: Spring Boot CI

on: [push]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_ACCESS_STRING: ${{ secrets.DB_ACCESS_STRING }}
      run: ./mvnw test

    - name: Build Docker image
      if: github.ref == 'refs/heads/main'
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_ACCESS_STRING: ${{ secrets.DB_ACCESS_STRING }}
      run: docker build . -t spring-boot-app

    - name: Run Docker container
      if: github.ref == 'refs/heads/main'
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_ACCESS_STRING: ${{ secrets.DB_ACCESS_STRING }}
      run: docker run -d --name spring-boot-testing -p 8080:8080 spring-boot-app

    - name: Health check
      if: github.ref == 'refs/heads/main'
      run: sleep 30 # Adjust based on your app's startup time
      
    - name: Set up Kubeconfig
      if: github.ref == 'refs/heads/main'
      env:
        KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG_CONTENTS" > ./kubeconfig
        echo "KUBECONFIG_FILE=./kubeconfig" >> $GITHUB_ENV

    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_ACCESS_STRING: ${{ secrets.DB_ACCESS_STRING }}
        KUBECONFIG_FILE: ./kubeconfig
      run: |
        kubectl --kubeconfig $KUBECONFIG_FILE apply -f deployment.yml
        kubectl --kubeconfig $KUBECONFIG_FILE rollout status deployment/spring-boot-app

    - name: Expose deployment
      if: github.ref == 'refs/heads/main'
      env:
        KUBECONFIG_FILE: ./kubeconfig
      run: |
        kubectl --kubeconfig $KUBECONFIG_FILE expose deployment spring-boot-app --type=NodePort --port=8081
